mysql:
  image: mysql:5.7
  env_file: docker/mysql/mysql.env
  environment:
    - TZ=Pacific/Honolulu
  ports:
    - '3306:3306'
  volumes:
    - ./docker/mysql/conf:/etc/mysql/conf.d/:ro
    - ./docker/mysql/data:/var/lib/mysql
